PUT https://api.distilld.io/search/filtered
Content-Type: application/json

{
  "searchQuery": "Clyde May's Straight Bourbon 0,7 l 46%",
  "tastingProfile": [],
  "whiskyType": [],
  "price": {
    "values": ["0", "900+"]
  },
  "country": [],
  "region": [],
  "rating": "",
  "sort": "_score-desc",
  "page": 1
}

###

POST https://api.whiskybase.com/api/v1/search
Content-Type: application/json

{
	"query": "Benriach Triple Distilled",
	"perpage": 2,
	"page": 1
}